services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: scisubmit
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9000:9000"
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

  # Database seeding
  seeder:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: [ "npx", "ts-node", "src/seed.ts" ]
    depends_on:
      - mongo

volumes:
  mongo_data:
