services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - avatars_data:/usr/src/app/uploads/avatars
      - docs_data:/usr/src/app/uploads/docs
    environment:
      - JWT_SECRET=my-super-secret-key
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf # Mount custom NGINX config
    depends_on:
      - backend

volumes:
  avatars_data:
  docs_data:
