networks:
  svk-network:

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: scisubmit
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - svk-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Named volume for persistent storage of uploaded files
      - project_storage:/app/uploads
    env_file:
      - ./backend/.env.dev  #Inject .env.dev dynamically
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - svk-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.dev
    ports:
      - "8080:8080"
      - "9000:9000"
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend
    networks:
      - svk-network

volumes:
  mongo_data:
  project_storage:
