kind: ConfigMap
apiVersion: v1
metadata:
  name: svk-fe-nginx
  namespace: svk
data:
  default.conf: |
    server {
      listen 80 default_server;
      index index.html;
      server_name _;
      error_log  /dev/stderr error;
      access_log off;
      root /usr/share/nginx/html;
    
      add_header Access-Control-Allow-Origin *;
      add_header Cache-Control max-age=86400;
      add_header X-Frame-Options SAMEORIGIN;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";
      add_header Referrer-Policy "no-referrer-when-downgrade";
    
      set_real_ip_from  10.0.0.0/8;
      real_ip_header    X-Forwarded-For;
      real_ip_recursive on;
    
    
      # GZIP compress
      # Dynamic mode
      gzip_vary on;
      gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/rss+xml application/xml image/svg+xml font/truetype font/opentype application/vnd.ms-fontobject;
      gzip_proxied expired no-cache no-store private auth;
      gzip_disable "MSIE [1-6]\.";
    
      # Static mode
      gzip_static on;    
    
      location / {
        sendfile       on;
        tcp_nopush     on;
        aio            on;
        expires 30d;
        try_files $uri $uri/ /index.html;
      }
    
      location /index.html {
        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control max-age=86400;
        add_header X-Frame-Options SAMEORIGIN;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy "no-referrer-when-downgrade";
    
    
        if_modified_since off;
        expires off;
        etag off;
      }
    }
